#!/usr/local/bin/fish
set BACKEND_FILES constants.coffee util.coffee vector.coffee quadtree.coffee
set BLOB_FILES gene.coffee blob.coffee environment.coffee
set MAIN_FILES $BACKEND_FILES $BLOB_FILES
set WEB_FILES $MAIN_FILES infoArea.coffee simulation.coffee
switch $argv[1]
	case web
		cat $WEB_FILES > web/combined.coffee
		coffee -c web/combined.coffee

	case quadtree_test
		cat $BACKEND_FILES test/quadtree.test > combined.coffee
		coffee combined.coffee

	case debug
		cat $MAIN_FILES test/debugSimulation.coffee > combined.coffee
		coffee combined.coffee
		
	case '*'
	    echo I need a command
end