#!/usr/local/bin/fish
set BACKEND_FILES coffee/util.coffee coffee/vector.coffee coffee/quadtree.coffee
set SIMULATION_FILES $BACKEND_FILES coffee/gene.coffee coffee/blob.coffee coffee/simulation.coffee
set FRONTEND_FILES coffee/renderer.coffee coffee/frontend.coffee

if test (count $argv) -eq 0
	set arg web
else
	set arg $argv[1]
end
switch $arg
	case web
		cat $SIMULATION_FILES > web/simulation.coffee
		cat $FRONTEND_FILES   > web/frontend.coffee
		coffee -c web/simulation.coffee
		coffee -c web/frontend.coffee
		cp lib/* web/lib
		python settings/process_settings.py
		cp settings/*.json web
		echo rebuilt the web files

	case quadtree_test
		cat $BACKEND_FILES test/quadtree.test > combined.coffee
		coffee combined.coffee

	case debug
		cat $MAIN_FILES test/debugSimulation.coffee > combined.coffee
		coffee combined.coffee

	case clear
		rm web/*.coffee
		rm web/*.js

	case '*'
	    echo Unrecognized command
end
